[package]
name = "lang-parse"
version = "0.1.0"
edition = "2024"

[dependencies]
common = { workspace = true }
clap = { workspace = true }
serde = { workspace = true }
tokio = { workspace = true }
futures = { workspace = true }
strum = { workspace = true }
tree-sitter = "0.26.13"
tree-sitter-rust = "0.24.2"
tree-sitter-javascript = "0.25.0"
